version: '3.8'

services:
  app:
    image: filipesag/hortifruti-api:latest
    ports:
      - "8080:8080"
    env_file:
      - .env.prod
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://${RDS_ENDPOINT}:5432/hortifruti
      SPRING_DATASOURCE_USERNAME: ${RDS_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${RDS_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: always
    networks:
      - hortifruti-network

networks:
  hortifruti-network:

